apiVersion: v1
kind: Service
metadata:
  name: hapi-fhir-svc
spec:
  selector:
    app: hapi-fhir
  type: NodePort
  ports:
    - name: hapi-fhir-http
      port: 8080
      targetPort: 8080
      nodePort: 30080
      protocol: TCP


